// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reducedCPE
double reducedCPE(NumericMatrix bMatrix, NumericMatrix gMatrix, NumericMatrix bKernel, NumericMatrix SurvMatrix);
RcppExport SEXP _SurvEval_reducedCPE(SEXP bMatrixSEXP, SEXP gMatrixSEXP, SEXP bKernelSEXP, SEXP SurvMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bMatrix(bMatrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type gMatrix(gMatrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bKernel(bKernelSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type SurvMatrix(SurvMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(reducedCPE(bMatrix, gMatrix, bKernel, SurvMatrix));
    return rcpp_result_gen;
END_RCPP
}
// sstartconcordance
double sstartconcordance(NumericVector Xbetahat, NumericVector Sstart, NumericVector Send);
RcppExport SEXP _SurvEval_sstartconcordance(SEXP XbetahatSEXP, SEXP SstartSEXP, SEXP SendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Xbetahat(XbetahatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Sstart(SstartSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Send(SendSEXP);
    rcpp_result_gen = Rcpp::wrap(sstartconcordance(Xbetahat, Sstart, Send));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurvEval_reducedCPE", (DL_FUNC) &_SurvEval_reducedCPE, 4},
    {"_SurvEval_sstartconcordance", (DL_FUNC) &_SurvEval_sstartconcordance, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurvEval(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
