# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reducedCPE <- function(bMatrix, gMatrix, bKernel, SurvMatrix) {
    .Call(`_SurvEval_reducedCPE`, bMatrix, gMatrix, bKernel, SurvMatrix)
}

sstartconcordance <- function(Xbetahat, Sstart, Send) {
    .Call(`_SurvEval_sstartconcordance`, Xbetahat, Sstart, Send)
}

